export const FETCHING_USERS = "action/FETCHING_USERS";
export const FETCHING_USERS_FAILED = "action/FETCHING_USERS_FAILED";
export const FETCHING_USERS_SUCCEEDED = "action/FETCHING_USERS_SUCCEEDED";
export const UPDATE_USER = "action/UPDATE_USER";
export const USER_SELECTED = "action/USER_SELECTED";
export const LOAD_USER_DETAILS = "action/LOAD_USER_DETAILS";
export const LOADING_USERS_DETAILS_FAILED =
  "action/LOADING_USERS_DETAILS_FAILED";
